site_name: ITMO NEWS

theme:
  name: null
  custom_dir: custom_theme
  
nav:
  - Main: index.md
  - Latest News: latest/index.md
  - Madia: media/index.md
  - Blog: media/index.md
  - Contacts: contacts/index.md