site_name: ITMO NEWS

nav:
  - Main: index.md
  - Latest News: latest/index.md
  - Madia: latest/index.md
  - Blog: latest/index.md
  - Contacts: latest/index.md
theme:
  name: null
  custom_dir: custom_theme
