site_name: ITMO NEWS

nav:
  - Main: index.md
  - Latest News: latest/index.md
  - Madia: media/index.md
  - Blog: meida/index.md
  - Contacts: contacts/index.md
theme:
  name: null
  custom_dir: custom_theme