name: Build and Deploy My Static Site on Github Pages

on:
  push:
      branches:
        - master

permissions:
  contents: write

job:
  build: 
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3

      - name: Python Setup
        uses: actions/setup-python@4
        with:
          pythons@3.x

      - name: Setup MkDocs
        run: pip install mkdocs

      - name: Build Site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
